<?php

namespace App\Utils\Enums;

class TodoEnums
{
    const SCENIC_MERCHANT_NOTICE = 100;
    const HOTEL_MERCHANT_NOTICE = 101;
    const CATERING_MERCHANT_NOTICE = 102;
    const GOODS_MERCHANT_NOTICE = 103;

    const AUTH_NOTICE = 200;
    const COMMISSION_WITHDRAWAL_NOTICE = 300;
    const SCENIC_INCOME_WITHDRAWAL_NOTICE = 400;
    const HOTEL_INCOME_WITHDRAWAL_NOTICE = 401;
    const CATERING_INCOME_WITHDRAWAL_NOTICE = 402;
    const GOODS_INCOME_WITHDRAWAL_NOTICE = 403;
    const REWARD_WITHDRAWAL_NOTICE = 500;

    const ORDER_SHIP_NOTICE = 600;
    const REFUND_NOTICE = 700;
}
